### PR TITLE
Add a writer option to graph->dot

### PR DESCRIPTION
**Pull request by CharlesHD**
Hi,
I use rhizome a lot, for quickly viewing small graphs or for parsing to dot large ones.
Actually, graph->dot build a string wich is memory consuming for parsing large graphs. I just slighty tweak the code in order to print these strings little by little to another writer than a StringBuilder. 

Normal behavior isn't affected `(graph->dot nodes fn-adj)` still return the dot string but you can do something like : 
```clojure
(with-open [wrt (clojure.java.io/writer "mycoolgraphfile.dot")]
  (graph->dot nodes fn-adj :writer wrt))
```
and it will print your dot to a file.

### CODE REVIEW

**Comment by ztellman** [comment]
Why not just write out the string returned by `graph->dot`?

**Comment by CharlesHD** [comment]
When you try to create a big graph ( like 100 000 nodes and 200 000 links ) that string is something like a huge number of chars stocked in RAM ( makes my jvm overhead ).
That can be processed a small string at a time.

Well this is a pretty specific case, but I work with these kind of graph.

**Comment by ztellman** [comment]
Okay, I figured it was something like that, but even 100k nodes should result in something like a 10mb string, right?  I wouldn't imagine that would cause too much overhead.

**Comment by CharlesHD** [comment]
You are completely right. I miscalculated the string impact, in fact my PR seems to consume even more memory than your actual code. I got luck this morning making the graph i'm working on pass. 
I'm on other machine this evening and things doesn't go that good.
So my scale problem clearly lies elsewhere.
I'm closing it, thank you for your time and your work ;).

**Comment by ztellman** [comment]
If you're using graphviz to render a file that large, I'm pretty sure the issue would be there.  The layout algorithms it uses don't scale that well.

**Comment by CharlesHD** [comment]
No, I'm using gephi. It handles large graph better than Graphviz. My problems come during the graph->dot phase. But I do not spot anything really memory consuming in the code.

**Comment by ztellman** [comment]
It's possible there's something quadratic in the string concatenation.  If you can give me a reproducing case, I'm happy to look at it myself.

**Comment by CharlesHD** [comment]
I was testing with range this far : 
```clojure
(graph->dot (range 10000) (fn [n] (range 1000)))
```

**Pull request closed without merging**
